apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: app-namespace
  labels:
    app: my-app
spec:
  selector:
    app: my-app
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: LoadBalancer