name: Create Vision One Container Security Policy

on:
  workflow_dispatch:
    inputs:
      ruleset_name:
        description: 'Ruleset Name'
        required: false
        default: 'DemoLogOnlyRuleset'
      policy_name:
        description: 'Policy Name'
        required: false
        default: 'DemoLogOnlyPolicy'

env:
  API_URL: https://api.xdr.trendmicro.com/beta/containerSecurity
  API_KEY: ${{ secrets.CONTAINER_SECURITY_API_KEY }}
  RULESET_NAME: ${{ github.event.inputs.ruleset_name }}
  POLICY_NAME: ${{ github.event.inputs.policy_name }}

jobs:
  check-policy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Check if Policy Exists
        run: |
          python trendmicro/scripts/check_policy.py

  check-ruleset:
    runs-on: ubuntu-latest
    needs: check-policy
    outputs:
      exists: ${{ steps.ruleset-check.outputs.exists }}
      ruleset_id: ${{ steps.ruleset-check.outputs.ruleset_id }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Check if Ruleset Exists
        id: ruleset-check
        run: |
          output=$(python trendmicro/scripts/check_ruleset.py)
          echo "$output"
          if echo "$output" | grep -q "exists=true"; then
            id=$(echo "$output" | awk -F'id=' '{print $2}')
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "ruleset_id=$id" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

  create-ruleset:
    runs-on: ubuntu-latest
    needs: check-ruleset
    if: needs.check-ruleset.outputs.exists == 'false'
    outputs:
      ruleset_id: ${{ steps.ruleset-create.outputs.ruleset_id }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create Ruleset
        id: ruleset-create
        run: |
          id=$(python trendmicro/scripts/create_ruleset.py | awk -F'=' '{print $2}')
          echo "ruleset_id=$id" >> $GITHUB_OUTPUT

  create-policy:
    runs-on: ubuntu-latest
    needs: [check-ruleset, create-ruleset]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Determine Ruleset ID
        id: ruleset-id
        run: |
          id=${{ needs.check-ruleset.outputs.ruleset_id }}
          if [ "$id" == "" ]; then
            id=${{ needs.create-ruleset.outputs.ruleset_id }}
          fi
          echo "RULESET_ID=$id" >> $GITHUB_ENV

      - name: Create Policy
        run: |
          python trendmicro/scripts/create_policy.py

  cleanup-ruleset:
    runs-on: ubuntu-latest
    needs: [create-policy, create-ruleset]
    if: failure() && needs.create-ruleset.result == 'success'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Delete Ruleset
        run: |
          python trendmicro/scripts/delete_ruleset.py
