name: Deploy Container Security with Policy Management

on:
  workflow_dispatch:
    inputs:
      cluster_name:
        description: 'EKS Cluster Name'
        required: true
        type: string
      region:
        description: 'AWS Region'
        required: true
        default: 'us-west-2'
        type: string
      group_id:
        description: 'Group ID'
        required: false
        default: '00000000-0000-0000-0000-000000000001'
        type: string
      ruleset_name:
        description: 'Ruleset Name'
        required: false
        default: 'DemoLogOnlyRuleset'
        type: string
      policy_name:
        description: 'Policy Name'
        required: false
        default: 'DemoLogOnlyPolicy'
        type: string

env:
  CLUSTER_NAME: ${{ github.event.inputs.cluster_name || vars.EKS_CLUSTER_NAME }}
  AWS_REGION: ${{ github.event.inputs.region || vars.AWS_REGION }}
  API_KEY: ${{ secrets.CONTAINER_SECURITY_API_KEY }}
  GROUP_ID: ${{ github.event.inputs.group_id }}
  RULESET_NAME: ${{ github.event.inputs.ruleset_name }}
  POLICY_NAME: ${{ github.event.inputs.policy_name }}
  POLICY_ID: ""
  POLICY_FILE: "trendmicro/policy.json"
  RULESET_FILE: "trendmicro/runtimeruleset.json"

jobs:
  manage-security-policies:
    runs-on: ubuntu-latest
    outputs:
      policy_id: ${{ steps.update-policy-id.outputs.policy_id }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml

      - name: Debug file structure
        run: |
          echo "Repository contents:"
          ls -la
          echo "Trendmicro directory:"
          ls -la trendmicro/
          echo "Trendmicro scripts:"
          ls -la trendmicro/scripts/

      - name: Check if ruleset exists
        id: check-ruleset
        run: |
          output=$(python trendmicro/scripts/check_ruleset.py)
          echo "$output"
        continue-on-error: true

      - name: Fail if ruleset exists
        if: steps.check-ruleset.outcome == 'success'
        run: |
          echo "Ruleset $RULESET_NAME already exists. Please use a different name and try again."
          exit 1

      - name: Create ruleset
        id: create-ruleset
        run: |
          python trendmicro/scripts/create_ruleset.py
          output=$(python trendmicro/scripts/check_ruleset.py)
          ruleset_id=$(echo "$output" | grep "ruleset_id=" | cut -d'=' -f2)
          echo "ruleset_id=$ruleset_id" >> $GITHUB_ENV
          echo "ruleset_id=$ruleset_id" >> $GITHUB_OUTPUT

      - name: Check if policy exists
        id: check-policy
        run: |
          output=$(python trendmicro/scripts/check_policy.py)
          echo "$output"
        continue-on-error: true

      - name: Fail if policy exists
        if: steps.check-policy.outcome == 'success'
        run: |
          echo "Policy $POLICY_NAME already exists. Please use a different name and try again."
          exit 1

      - name: Create policy
        id: create-policy
        run: |
          python trendmicro/scripts/create_policy.py
          output=$(python trendmicro/scripts/check_policy.py)
          policy_id=$(echo "$output" | grep "policy_id=" | cut -d'=' -f2)
          echo "policy_id=$policy_id" >> $GITHUB_ENV
          echo "policy_id=$policy_id" >> $GITHUB_OUTPUT

      - name: Update Policy ID Output
        id: update-policy-id
        run: |
          echo "policy_id=${{ env.policy_id }}" >> $GITHUB_OUTPUT

  deploy-container-security:
    needs: manage-security-policies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update kube config
        run: |
          aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_REGION
          kubectl cluster-info
          kubectl get nodes

      - name: Setup Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh

      - name: Create Helm overrides file
        run: |
          cat <<EOF > overrides.yaml
          cloudOne:
            clusterRegistrationKey: true
            groupId: $GROUP_ID
            policyId: ${{ needs.manage-security-policies.outputs.policy_id }}
            endpoint: https://container.us-1.cloudone.trendmicro.com
            exclusion:
              namespaces: [kube-system]
            runtimeSecurity:
              enabled: true
            vulnerabilityScanning:
              enabled: true
            malwareScanning:
              enabled: true
            inventoryCollection:
              enabled: true
          EOF

      - name: Create namespace and secret
        run: |
          kubectl create namespace trendmicro-system --dry-run=client -o yaml | kubectl apply -f -
          kubectl delete secret trendmicro-container-security-registration-key -n trendmicro-system --ignore-not-found
          kubectl create secret generic trendmicro-container-security-registration-key -n trendmicro-system --from-literal=registration.key=$API_KEY

      - name: Deploy with Helm
        run: |
          helm install trendmicro --namespace trendmicro-system --values overrides.yaml https://github.com/trendmicro/cloudone-container-security-helm/archive/master.tar.gz

      - name: Verify deployment
        run: |
          kubectl get pods -n trendmicro-system
          kubectl get services -n trendmicro-system

      - name: Save Deployment Info
        run: |
          cat <<EOF > deployment-info.json
          {
            "clusterName": "$CLUSTER_NAME",
            "region": "$AWS_REGION",
            "policyId": "${{ needs.manage-security-policies.outputs.policy_id }}",
            "deployedAt": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
          }
          EOF

      - name: Upload Deployment Info Artifact
        uses: actions/upload-artifact@v4
        with:
          name: deployment-info
          path: deployment-info.json
          retention-days: 90
