name: Deploy Container Security with Policy Management

on:
  workflow_dispatch:
    inputs:
      customer_name:
        description: 'Customer Name'
        required: true
        default: 'DemoCluster001'

jobs:
  manage-security-policies:
    runs-on: ubuntu-latest
    env:
      CLUSTER_NAME: ${{ github.event.inputs.customer_name }}
      AWS_REGION: us-west-2
      API_KEY: ${{ secrets.TRENDMICRO_API_KEY }}
      GROUP_ID: '00000000-0000-0000-0000-000000000001'
      RULESET_NAME: 'DemoLogOnlyRuleset'  # Changed to match the name in the JSON file
      POLICY_NAME: 'DemoLogOnlyPolicy'    # Changed to match the name in the JSON file
      POLICY_FILE: trendmicro/policy.json
      RULESET_FILE: trendmicro/runtimeruleset.json

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml

      - name: Make scripts executable
        run: |
          chmod +x trendmicro/scripts/*.py

      - name: Manage Security Policies
        run: |
          # Using the bash script to handle the logic
          bash trendmicro/scripts/manage-security-policies.sh
